### ISSUE TITLE
alexis/util/struct: lexical context and using `define-struct-updaters` within another macro

### ISSUE THREAD

**Issue by AlexKnauth** [lexi-lambda/racket-alexis#1]
Right now, it seems like the identifiers generated by `define-struct-updaters` have the lexical context of the outer parens, instead of the struct id or the result of `(syntax-local-introduce #'here)`, or something.

Did you intend that, and if not would it be a good idea to change that to use either the struct id or `syntax-local-introduce`, and document that so that other macros can compose with it more easily? Or if that was what you meant to do, should you document that anyway?

**Comment by AlexKnauth** [comment]
By the way I'm going by this [racket users list thread](http://lists.racket-lang.org/users/archive/2013-October/059736.html), and more specifically [this](http://lists.racket-lang.org/users/archive/2013-October/059737.html), [this](http://lists.racket-lang.org/users/archive/2013-October/059739.html), and [this](http://lists.racket-lang.org/users/archive/2013-October/059741.html).

**Comment by lexi-lambda** [comment]
That's a reasonable point. I've changed it to use the lexical context of the struct id in 23141965df8364235ca433f5e894fad14ae6d0c6. Thanks for the report.

**Comment by AlexKnauth** [comment]
Thanks!
