### ISSUE TITLE
alexis/util/struct: would it make sense to provide some version of the `get-struct-accessors` helper function?

### ISSUE THREAD

**Issue by AlexKnauth** [lexi-lambda/racket-alexis#2]
Would it make sense to provide the `get-struct-accessors` helper function, or some version of it, so that I, or someone else, could use it to define other similar macros?

**Comment by lexi-lambda** [comment]
Perhaps it could be put in a submodule?

**Comment by AlexKnauth** [comment]
That would work. Whatever makes the most sense to you
